{
  this.chain.setLastCallable(new Callable<Object>(){
    public Object call() throws Exception {
      return 1;
    }
  }
);
  this.asyncWebRequest.startAsync();
  this.asyncWebRequest.complete();
  this.chain.startCallableProcessing();
  Exception ex=this.resultSavingCallable.exception;
  assertNotNull(ex);
  assertEquals(StaleAsyncWebRequestException.class,ex.getClass());
}
