{
  return (this.applicationException != null ? this.applicationException : getCause());
}
