{
  try {
    this.chain.startCallableProcessing();
    fail("Expected exception");
  }
 catch (  IllegalStateException ex) {
    assertEquals(ex.getMessage(),"The last Callable was not set");
  }
}
