{
  List<Throwable> errors=new ArrayList<Throwable>();
  try {
    this.next.evaluate();
  }
 catch (  Throwable ex) {
    errors.add(ex);
  }
  try {
    this.testContextManager.afterTestClass();
  }
 catch (  Throwable ex) {
    errors.add(ex);
  }
  MultipleFailureException.assertEmpty(errors);
}
