{
  final HttpClientErrorException[] callbackException=new HttpClientErrorException[1];
  ListenableFuture<?> future=template.execute(baseUrl + "/status/notfound",HttpMethod.GET,null,null);
  future.addCallback(new ListenableFutureCallback<Object>(){
    @Override public void onSuccess(    Object result){
      fail("onSuccess not expected");
    }
    @Override public void onFailure(    Throwable t){
      assertTrue(t instanceof HttpClientErrorException);
      callbackException[0]=(HttpClientErrorException)t;
    }
  }
);
  try {
    future.get();
    fail("Exception expected");
  }
 catch (  ExecutionException ex) {
    Throwable cause=ex.getCause();
    assertTrue(cause instanceof HttpClientErrorException);
    assertSame(callbackException[0],cause);
  }
}
