{
  Throwable exception=new RuntimeException();
  boolean wasSet=settableListenableFuture.setException(exception);
  assertTrue(wasSet);
  try {
    settableListenableFuture.get();
    fail("Expected ExecutionException");
  }
 catch (  ExecutionException ex) {
    assertThat(ex.getCause(),equalTo(exception));
  }
}
