{
  Throwable exception=new RuntimeException();
  final Throwable[] callbackHolder=new Throwable[1];
  settableListenableFuture.addCallback(new ListenableFutureCallback<String>(){
    @Override public void onSuccess(    String result){
      fail("Expected onFailure() to be called");
    }
    @Override public void onFailure(    Throwable t){
      callbackHolder[0]=t;
    }
  }
);
  settableListenableFuture.setException(exception);
  assertFalse(settableListenableFuture.setException(new IllegalArgumentException()));
  assertThat(callbackHolder[0],equalTo(exception));
}
