{
  try {
    return executeAsync().get();
  }
 catch (  InterruptedException ex) {
    throw new IOException(ex.getMessage(),ex);
  }
catch (  ExecutionException ex) {
    Throwable cause=ex.getCause();
    if (cause instanceof IOException) {
      throw (IOException)cause;
    }
    throw new IOException(cause.getMessage(),cause);
  }
}
