{
  return (this.exception instanceof InvocationTargetException);
}
